//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arma3Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("arma3Launcher.Properties.GlobalValues", typeof(GlobalValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/serialtasted/arma3Launcher.
        /// </summary>
        internal static string Link_Gihub {
            get {
                return ResourceManager.GetString("Link_Gihub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.twitch.tv/serialtasted.
        /// </summary>
        internal static string Link_Twitch {
            get {
                return ResourceManager.GetString("Link_Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/serialtasted.
        /// </summary>
        internal static string Link_Twitter {
            get {
                return ResourceManager.GetString("Link_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/serialtasted.
        /// </summary>
        internal static string Link_Youtube {
            get {
                return ResourceManager.GetString("Link_Youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://ptrddns.dlinkddns.com/arma3Launcher/PackImgs2/.
        /// </summary>
        internal static string S_PackImgsDir {
            get {
                return ResourceManager.GetString("S_PackImgsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://ptrddns.dlinkddns.com/arma3Launcher/Repo/.
        /// </summary>
        internal static string S_RepoAddress {
            get {
                return ResourceManager.GetString("S_RepoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://ptrddns.dlinkddns.com/arma3Launcher/Repo/repoList.a3l.
        /// </summary>
        internal static string S_RepoList {
            get {
                return ResourceManager.GetString("S_RepoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://ptrddns.dlinkddns.com/arma3Launcher/Releases/zUpdator.exe.
        /// </summary>
        internal static string S_UpdateUrl {
            get {
                return ResourceManager.GetString("S_UpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string S_VersionTag {
            get {
                return ResourceManager.GetString("S_VersionTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://ptrddns.dlinkddns.com/arma3Launcher/Configs/config.xml.
        /// </summary>
        internal static string S_VersionXML {
            get {
                return ResourceManager.GetString("S_VersionXML", resourceCulture);
            }
        }
    }
}
